module.exports = [
  {
    question: "Which heart chamber pumps deoxygenated blood into the pulmonary artery?",
    A: "Left atrium",
    B: "Right ventricle",
    C: "Left ventricle",
    D: "Right atrium",
    correctAnswer: "B",
    explanation: "The right ventricle sends deoxygenated blood through the pulmonary artery to the lungs.",
  },
  {
    question: "Which vitamin deficiency is classically associated with scurvy?",
    A: "Vitamin A",
    B: "Vitamin B12",
    C: "Vitamin C",
    D: "Vitamin D",
    correctAnswer: "C",
    explanation: "Scurvy occurs because vitamin C deficiency impairs collagen synthesis.",
  },
  {
    question: "What is the normal adult resting heart rate range?",
    A: "20-40 beats per minute",
    B: "40-50 beats per minute",
    C: "60-100 beats per minute",
    D: "120-160 beats per minute",
    correctAnswer: "C",
    explanation: "A normal adult resting heart rate is commonly 60-100 beats per minute.",
  },
  {
    question: "Which cell type produces antibodies?",
    A: "Neutrophils",
    B: "Plasma cells",
    C: "Erythrocytes",
    D: "Platelets",
    correctAnswer: "B",
    explanation: "Plasma cells are differentiated B cells that secrete antibodies.",
  },
  {
    question: "Which organ is the primary site of bile production?",
    A: "Gallbladder",
    B: "Pancreas",
    C: "Liver",
    D: "Duodenum",
    correctAnswer: "C",
    explanation: "The liver produces bile; the gallbladder stores and concentrates it.",
  },
  {
    question: "Which structure filters blood to form the initial filtrate in the kidney?",
    A: "Glomerulus",
    B: "Loop of Henle",
    C: "Collecting duct",
    D: "Ureter",
    correctAnswer: "A",
    explanation: "The glomerulus filters plasma into Bowman's capsule.",
  },
  {
    question: "Which neurotransmitter is primarily reduced in Parkinson disease?",
    A: "Serotonin",
    B: "Dopamine",
    C: "Acetylcholine",
    D: "Glutamate",
    correctAnswer: "B",
    explanation: "Parkinson disease involves loss of dopaminergic neurons in the substantia nigra.",
  },
  {
    question: "Which blood type is considered the universal red blood cell donor?",
    A: "A positive",
    B: "AB positive",
    C: "O negative",
    D: "B negative",
    correctAnswer: "C",
    explanation: "O negative red blood cells lack A, B, and Rh D antigens.",
  },
];
